--CREATE SOME DATA FOR TESTING
-- TEMPLATE
INSERT INTO SYS_USR VALUES ();
INSERT INTO ROLE VALUES ();
INSERT INTO ROLE_FUNC VALUES();
INSERT INTO ROLE_MEM VALUES();

-- TOM
INSERT INTO SYS_USR VALUES ();
INSERT INTO ROLE VALUES ();
INSERT INTO ROLE_FUNC VALUES();
INSERT INTO ROLE_MEM VALUES();

-- SUP
INSERT INTO SYS_USR VALUES ();
INSERT INTO ROLE VALUES ();
INSERT INTO ROLE_FUNC VALUES();
INSERT INTO ROLE_MEM VALUES();

-- INV
INSERT INTO SYS_USR VALUES ('INA','123456','INACTIVE', SYSDATE,'N',0,'N');
INSERT INTO ROLE VALUES ('I1','THIS IS INA USER 1','N','USR',SYSDATE);
INSERT INTO ROLE_FUNC VALUES('I1','IF1','N','N','N','N','N');
INSERT INTO ROLE_MEM VALUES('I1','INA');

-- EXP
INSERT INTO SYS_USR VALUES ('EXP','123456','EXPIRED',SYSDATE,'Y',0,'N');
INSERT INTO ROLE VALUES ('I2','THIS IS EXP USER','Y','USR',SYSDATE);
INSERT INTO ROLE_FUNC VALUES('I2','IF2','Y','Y','Y','Y','Y');
INSERT INTO ROLE_MEM VALUES('I2','EXP');