select * from tm;
select * from tm_own;
select * from tm_cat;
select * from category;
select * from reg_owner;
select * from edi_queue;
select * from edi_error;
select * from edi_owner_temp;
select * from edi_cat_temp;